Feature/astro
Justyanna/toy-box pull request #6
Opened 2024-05-13 20:21 UTC by Justyanna

- I added nanostores for state menaging through components
- There is no astro solution for notifications

2024-05-28 16:54 UTC, abraham-kaczmarski requested changes
Mostly fine, some conventions need to be discussed and explicitly defined.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/README.md
Remove or rename the generated README and bootstrap a proper one for the project.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/public/locales/en/translation.json
Do you guys think we should agree on a convention for the translation keys?
It usually comes back to bite me in the ass sooner than later.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/components/Footer.astro
Add a copyright string to at least have the component rendered.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/components/Header.astro
Add a logo placeholder (a string is fine) to at least have the component rendered.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/components/Room.astro
The room should probably take room id as a prop and generate a valid url based on that.
The `url` prop seems like an invitation for inconsistency or security issues.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/content/config.ts
Have we agreed on Astro collection + Makrdown aproach or is the plan to switch it to plain Typescript?

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/layouts/BaseLayout.astro
Are you sure about this `<h1/>`?
If a page needs a heading, it can define it in it's own source code.
Current aproach may hinder some common design patterns, breadcrumbs for example.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/layouts/GameLayout.astro
> +const { frontmatter } = Astro.props;
Does frontmatter refer metadata? Either accept a complete game model or individual props (seriously, the former though). Perhaps just a naming issue?

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/layouts/RoomLayout.astro
> +const { frontmatter } = Astro.props;
The `frontmatter` argument yet again.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/pages/games/[...slug].astro
> +}
Could we move all of the imperative code to `.ts` files (service layer) and keep the `.astro` files declarative as a convention?

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/src/pages/rooms/[...slug].astro
> +}
Imperative code - part of bigger discussion.

2024-05-28 16:54 UTC, abraham-kaczmarski commented on app-website/tsconfig.json
Have we researched good config defaults or was this generated?

2024-06-04 12:32 UTC, Justyanna commented on app-website/public/locales/en/translation.json
Yeah, we probably shouldnt - sooner or later it will be giant mess with those.

2024-06-06 16:50 UTC, Justyanna commented on app-website/tsconfig.json
Have we researched good config defaults? yes and still dont know if it good or not
was this generated? it was

2024-06-06 16:52 UTC, Justyanna commented on app-website/src/content/config.ts
The plan is to switch it to plain Typescript

2024-06-13 15:37 UTC, abraham-kaczmarski approved these changes
LGTM

2024-06-13 15:41 UTC, merged