4 server initialization
Justyanna/toy-box pull request #7
Opened 2024-05-16 15:55 UTC by Hekard

- Added gin project with zap-logger and golang-migrate
- Added jwt token middleware

2024-05-27 15:08 UTC, Justyanna commented on app-server/internal/repository/db.go
> +		"file://"+migrationsDir,
Formatowanko

2024-05-27 15:09 UTC, Justyanna commented on app-server/internal/mock/mockTokenHandler.go
> +		"exp":    expirationTime.Unix(),
Formatowanko

2024-05-27 15:14 UTC, Justyanna commented on app-server/internal/auth/authMiddleware.go
> +func AuthMiddleware(secret_byte []byte) gin.HandlerFunc {
To bym podzieliła na mniejsze funkcje

2024-05-28 17:10 UTC, abraham-kaczmarski requested changes
Good start, we need to agree on some conventions.

2024-06-20 16:27 UTC, abraham-kaczmarski requested changes
Just some more cleanup.

2024-06-20 16:27 UTC, abraham-kaczmarski commented on app-server/internal/utilis/environment.go
Fix package name.

2024-06-20 16:27 UTC, abraham-kaczmarski commented on app-server/internal/utilis/environment.go
> +func getSecretKey() []byte {
What about other getters?

2024-06-20 16:54 UTC, abraham-kaczmarski approved these changes
LGTM

2024-06-23 14:29 UTC, merged